baseURL = 'https://patel-sumit.web.app/'
languageCode = 'en-us'
title = 'Dark-Kernel'
linkTitle = "Navigation and Search"
theme = 'ananke'
[outputs]
  home = ["HTML", "RSS", "JSON"]


[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
	identifier = "about"
	name= "About"
	url = "/about"
	weight = 3
[[menu.main]]
	identifier = "blog"
	name= "Blogs"
	url = "/posts/"
	weight = 2
[[menu.main]]
	identifier = "contact"
	name= "Contact"
	url = "/contact"
	weight = 4


#[[params.ananke_socials]]
#name = "github"
#url = "https://github.com/Dark-Kernel"
#[[menu.blog]]
#    name = "Blog"
#    weight = 40



disqusShortname = 'shrtdisq'


[params.shareButtons]
  networks = ["facebook", "twitter", "email", "linkedin", "reddit"]
  size = "small"
  buttonMargin = "0.2em"
  icon = "solid"

offlineSearch = true
